name: Caosai
url: http://icaosai.github.io
description: Insert tagline here

permalink: /themes/:title/

highlighter: pygments
paginate: 10

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
